# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o ./output/wkgo.exe -v ./...

      - name: Test
        run: go test -v ./...

      - name: Commit and Push
        run: |
          git config --global user.name "Armando Peña Tamayo"
          git config --global user.email "arman2p284@gmail.com"
          git add ./output/wkgo.exe
          git commit -m "Feat: Add latest built executable"
          git push
